import { jsPDF } from "jspdf";

// Turn a chat answer into a clean one-page PDF the patient can send to a
// family member or caregiver. Markdown bold markers are stripped.
export function shareAnswerPdf({ patientName, procedure, content }) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const margin = 56;
  const width = doc.internal.pageSize.getWidth() - margin * 2;
  let y = margin;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(11, 118, 128);
  doc.text("AllClear", margin, y);
  y += 24;

  doc.setFontSize(11);
  doc.setTextColor(60, 80, 90);
  doc.setFont("helvetica", "normal");
  const meta = [
    patientName ? `Patient: ${patientName}` : null,
    procedure ? `Procedure: ${procedure}` : null,
    `Prepared: ${new Date().toLocaleString()}`,
  ]
    .filter(Boolean)
    .join("   ·   ");
  doc.text(meta, margin, y);
  y += 10;
  doc.setDrawColor(18, 165, 176);
  doc.setLineWidth(1.2);
  doc.line(margin, y, margin + width, y);
  y += 24;

  doc.setFontSize(12);
  doc.setTextColor(23, 50, 59);
  const clean = content.replace(/\*\*(.+?)\*\*/gs, "$1");
  const lines = doc.splitTextToSize(clean, width);
  for (const line of lines) {
    if (y > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      y = margin;
    }
    doc.text(line, margin, y);
    y += 18;
  }

  y += 14;
  if (y > doc.internal.pageSize.getHeight() - margin - 30) {
    doc.addPage();
    y = margin;
  }
  doc.setFontSize(9);
  doc.setTextColor(120, 135 , 143);
  doc.text(
    "Generated by AllClear from the patient's care instructions. Not a substitute for the care team's advice.",
    margin,
    y
  );

  doc.save(`AllClear_${(procedure || "care_note").replace(/\W+/g, "_")}.pdf`);
}
